"""Render metrics.md (the brief's template) from bench/report.json. No number is typed by hand."""
from __future__ import annotations

import json
import sys
from pathlib import Path


def _ok(val, target, higher=True) -> str:
    if val is None:
        return "n/a"
    return "✅" if (val >= target if higher else val <= target) else "❌"


def _f(v, unit="") -> str:
    return "n/a" if v is None else f"{v}{unit}"


def write_metrics(r: dict, path: Path) -> None:
    c, lat, acc, cache = r["compliance"], r["latency"], r["accuracy"], r["cache"]
    env = r["env"]
    L = []
    w = L.append
    w("# System Performance Metrics & Evaluation Report")
    w("")
    if r.get("synthetic_kit"):
        w("> **Measured on the SYNTHETIC starter kit** (`data/`, generated by `scripts/make_synthetic_kit.py`), not the "
          "official Samsung data. `python bench/run.py` re-runs unchanged once the official files are dropped into `data/`.")
        w("")
    w(f"**Model(s):** {r['llm']} · request-path modes: enrichment `{r.get('enrich_mode')}`, extraction "
      f"`{r['extract_mode']}` (auto routing: a CPU-local SLM runs off the request path; deterministic fallback "
      "when no LLM is reachable)  ")
    w(f"**Embeddings:** retrieval {r['embed_model']} · semantic cache {r.get('cache_embed_model')} · reranker {r['rerank_model']}  ")
    w(f"**Environment:** {env.get('cpu')} · {env.get('logical_cpus')} logical CPUs (torch threads {env.get('torch_threads')}) · "
      f"{_f(env.get('ram_gb'), ' GB')} RAM · {env.get('os')} · Python {env.get('python')} · power: {env.get('power', 'unknown')}  ")
    w(f"**Generated:** {r['generated']} by `bench/run.py` in {r['bench_seconds']} s")
    if r.get("reused_llm_sections_from"):
        ru = r["reused_llm_sections_from"]
        w("")
        w(f"**Note:** the cache-independent LLM sections (LLM deeplink baseline, LLM extraction modes, provider "
          f"profiles) are copied from the full run of {ru['generated']} (`{ru['file']}`); everything else is from this run.")
    w("")
    w("---")
    w("")
    w("## 1. Schema & Rule Compliance")
    w(f"Evaluated on every line of `results.jsonl` ({c['lines']} queries from `queries.json`, replayed in order "
      "against a cache that starts empty and fills as validated plans are written, as in production).")
    w("")
    w("| Metric | Target | Measured Value | |")
    w("| :--- | :--- | :--- | :-: |")
    w(f"| Schema-valid output lines | >= 99% | {c['schema_valid_pct']}% | {_ok(c['schema_valid_pct'], 99)} |")
    w(f"| Rule compliance (all 11 checks incl. Goal / Title / Description syntax) | >= 95% | {c['rule_compliance_pct']}% | {_ok(c['rule_compliance_pct'], 95)} |")
    w(f"| Absolute URL leaks | 0 | {c['url_leaks']} | {_ok(c['url_leaks'], 0, higher=False)} |")
    w(f"| Deeplink catalog validity (exact URI match, or `dummy_positive`) | 100% | {c['catalog_validity_pct']}% "
      f"({c['deeplinks']} deeplinks, {c['dummy_positive']} dummy_positive) | {_ok(c['catalog_validity_pct'], 100)} |")
    w(f"| Auto actions carrying valid actionable deeplink | >= 90% | {_f(c['auto_with_deeplink_pct'], '%')} "
      f"({c['auto_actions']} auto actions) | {_ok(c['auto_with_deeplink_pct'], 90)} |")
    w("")
    w("Violations by check (after auto-fix): " + ", ".join(f"`{k}` {v}" for k, v in c["violations_by_check"].items()))
    w("")
    ro = r["routing"]
    w(f"Routing on `queries.json`: single-symptom correct article {ro.get('single_correct', 0)}, wrong article "
      f"{ro.get('single_wrong', 0)}, false no_match {ro.get('single_no_match', 0)}; multi-symptom both goals "
      f"{ro.get('multi_both', 0)}, partial {ro.get('multi_partial', 0)}; expected no_match correctly refused "
      f"{ro.get('no_match_correct', 0)}, answered anyway {ro.get('no_match_false_plan', 0)}.")
    w("")
    w("---")
    w("")
    w("## 2. Accuracy Benchmarks")
    w("Evaluated against the 5 gold samples (`data/samples/`), each run twice: with the gold SIIS text supplied "
      "(`siis_response`), and with retrieval from `siis_responses.json`. Scoring helper: `bench/scoring.py`.")
    w("")
    w("| Evaluation Metric | Scale / Anchor | Score |")
    w("| :--- | :--- | :--- |")
    w(f"| Step accuracy (completeness, correctness, ordering) | 0.0 - 3.0 | {acc['mean_step_accuracy']} |")
    w(f"| Deeplink relevance (exact target screen vs. parent menu) | 0.0 - 2.0 | {acc['mean_deeplink_relevance']} |")
    w("")
    w("| Sample | SIIS | Step acc. | Complete / Correct / Order | Deeplink | Notes for manual review |")
    w("| :--- | :--- | :-: | :-: | :-: | :--- |")
    for row in acc["rows"]:
        cco = (f"{row.get('completeness', '-')} / {row.get('correctness', '-')} / {row.get('ordering', '-')}"
               if "completeness" in row else "-")
        w(f"| {row['sample']} | {'supplied' if row['grounded'] else 'retrieved'} | {row['step_accuracy']} | {cco} | "
          f"{row['deeplink_relevance']} | {row['note']} |")
    w("")
    dl = r["ablation_deeplink"].get("hybrid", {})
    w(f"Screen-resolution accuracy on all {dl.get('n')} screen-level actions in the SIIS corpus (gold = menu path in the "
      f"article): **{dl.get('exact_screen_pct')}% exact screen**, {dl.get('parent_or_dummy_pct')}% parent/dummy.")
    w("")
    w("---")
    w("")
    w("## 3. Latency Benchmarks (N >= 30 per path)")
    w("In-process timings through `Engine.troubleshoot` (the same code the API calls; HTTP adds ~1-3 ms).")
    w("")
    w("| Execution Path | Target (P95) | N | P50 (ms) | P95 (ms) | |")
    w("| :--- | :--- | :-: | :-: | :-: | :-: |")
    e, p, pc, cold = lat["exact_hit"], lat["paraphrase_hit_raw"], lat["paraphrase_hit_canonical"], lat["cold"]
    w(f"| Cache hit - exact query match | <= 300 ms | {e['n']} | {_f(e['p50'])} | {_f(e['p95'])} | {_ok(e['p95'], 300, False)} |")
    w(f"| Cache hit - unseen semantic paraphrase (key + article tiers, 0 LLM calls) | <= 300 ms | {p['n']} | {_f(p['p50'])} | {_f(p['p95'])} | {_ok(p['p95'], 300, False)} |")
    if "key_tier" in p:
        w(f"| &nbsp;&nbsp;of which key tier / article-anchored tier | <= 300 ms | {p['key_tier']['n']} / {p['article_tier']['n']} | | "
          f"{_f(p['key_tier']['p95'])} / {_f(p['article_tier']['p95'])} | |")
    w(f"| Cache hit - paraphrase via canonical lookup (after SLM enrichment) | - | {pc['n']} of {pc.get('tried')} tried | {_f(pc['p50'])} | {_f(pc['p95'])} | |")
    w(f"| Cold query - full pipeline extraction & mapping | <= 8000 ms | {cold['n']} | {_f(cold['p50'])} | {_f(cold['p95'])} | {_ok(cold['p95'], 8000, False)} |")
    w("")
    w(f"Cold path: models {', '.join(cold['models'])}; mean {cold['llm_calls_mean']} LLM calls, "
      f"{cold['tokens_in_mean']} prompt / {cold['tokens_out_mean']} completion tokens per query. "
      f"Stage P50 (ms): " + ", ".join(f"{k.replace('_ms', '')} {v}" for k, v in cold["stage_p50_ms"].items()) + ".")
    w(f"LLM calls made on cache hits: {lat['cache_hit_llm_calls']}. `results.jsonl` replay (mix of cold and cached): P50 "
      f"{r['results_cold_latency']['p50']} ms, P95 {r['results_cold_latency']['p95']} ms.")
    w("")
    w("---")
    w("")
    w("## 4. Operational Cost & Cache Efficacy")
    m = cache["primary"]
    tau = f"{r['tau']:.2f}"
    w("")
    w("| Metric Item | Target | Measured Value |")
    w("| :--- | :--- | :--- |")
    w(f"| Cold query average inference cost | Tracked | ${cold['cost_usd_mean']:.6f} |")
    w(f"| Cache hit inference cost | $0.00 | $0.00 ({lat['cache_hit_llm_calls']} LLM calls on hits) |")
    hr = m["by_tau"][tau]["hit_rate_pct"] if tau in m["by_tau"] else None
    w(f"| Semantic cache hit rate (on unseen paraphrases, raw lookup, τ={tau}) | >= 80% | {hr}% {_ok(hr, 80)} |")
    du = cache["dual_lookup"]
    w(f"| Semantic cache hit rate, zero-LLM tiers (key → article-anchored), τ={du['tau']:.2f} | >= 80% | "
      f"{du['zero_llm_hit_pct']}% {_ok(du['zero_llm_hit_pct'], 80)} |")
    w(f"| Semantic cache hit rate, all tiers (key → article → canonical key after enrichment) | >= 80% | "
      f"{du['dual_hit_pct']}% {_ok(du['dual_hit_pct'], 80)} |")
    w(f"| Wrong-plan hits / negatives hit (all tiers) | low | {du['wrong_hits']} of {du['n']} paraphrases "
      f"(by tier {du['wrong_by_tier']}) / {du['negatives_hit']} of {du['negatives']}; false-hit rate "
      f"{du['false_hit_rate_pct']}% of hits |")
    w("| Cost derivation method | - | (prompt tokens × input rate + completion tokens × output rate); local SLM = $0 |")
    w("")
    w("Tiers: ② key lookup on the raw query (FAISS, τ); ②b article-anchored: on a key miss, a dense-only SIIS match "
      "(min similarity and margin over the runner-up article) reuses the validated plan already cached for that article "
      "- the same grounding the cold path would use; ②c canonical key lookup after SLM enrichment.")
    w("")
    w(f"τ sweep (key tier only): {m['paraphrases']} held-out paraphrases (never pre-warmed) + {m['negatives']} unseen negatives against "
      f"{m['keys']} cache keys / {m['plans']} plans. Hit = top key ≥ τ and its plan is grounded in the expected article; "
      "false hit = hit on the wrong plan or on a negative.")
    w("")
    w("| Embedding | τ | Hit rate | Any hit | False hits | False-hit rate (of hits) | Negatives hit |")
    w("| :--- | :-: | :-: | :-: | :-: | :-: | :-: |")
    for name in ("primary", "compare"):
        if name not in cache:
            continue
        for t, v in cache[name]["by_tau"].items():
            w(f"| {cache[name]['embed_model']} | {t} | {v['hit_rate_pct']}% | {v['any_hit_pct']}% | {v['false_hits']} | "
              f"{v['false_hit_rate_pct']}% | {v['negatives_hit']} |")
    w("")
    w("---")
    w("")
    w("## 5. Architectural Ablation Analysis")
    w("Deeplink mapping variants on the SIIS-derived screen set (step text is identical across these variants, so "
      "step accuracy is reported from the gold-sample run of the full pipeline):")
    w("")
    w("| Architecture Variant | Step Accuracy | Exact screen | Mean relevance (0-2) | Latency P95 / action | Cost / action | Key Observations |")
    w("| :--- | :-: | :-: | :-: | :-: | :-: | :--- |")
    names = {"llm": "Baseline: Full LLM Deeplink Mapping", "hybrid": "Variant A: Hybrid BM25 + Dense + RRF + CE (ours)",
             "bm25": "Variant B: Pure Rules/Keyword (BM25 top-1)", "dense": "Variant C: Dense-only top-1"}
    ab = r["ablation_deeplink"]
    for k in ("llm", "hybrid", "bm25", "dense"):
        if k not in ab:
            if k == "llm":
                w(f"| {names[k]} | - | not measured | - | - | - | no LLM reachable during this run |")
            continue
        v = ab[k]
        obs = f"n={v['n']}"
        if k == "hybrid":
            obs += "; specificity tie-break picks the deepest named screen over its parent"
        w(f"| {names[k]} | {acc['mean_step_accuracy']} | {v['exact_screen_pct']}% | {v['mean_relevance']} | "
          f"{v['p95_ms_per_action']} ms | ${v['cost_usd_per_action']:.6f} | {obs} |")
    w("")
    w("Extraction variants on the 5 gold samples (SIIS supplied):")
    w("")
    w("| Extraction | Step Accuracy (0-3) | Deeplink relevance (0-2) | Latency P95 | Cost / query |")
    w("| :--- | :-: | :-: | :-: | :-: |")
    for k, v in r["ablation_extraction"].items():
        w(f"| {k} | {v['mean_step_accuracy']} | {v['mean_deeplink_relevance']} | {v['p95_latency_ms']} ms | ${v['mean_cost_usd']:.6f} |")
    w("")
    bu = r.get("background_upgrade")
    if bu:
        w(f"Background SLM paraphrase upgrade (mode `{bu['mode']}`): {bu['plans_with_llm_variations']} cached plans "
          f"received SLM-written variations as extra keys; the benchmark waited {bu['wait_s']} s for the queue to drain "
          "before measuring the cache.")
        w("")
    w("Local SLM vs hosted fallback, full-LLM profile inline (SLM enrichment + SLM pointer extraction), cold "
      "queries on held-out paraphrases:")
    w("")
    w("| Provider | Model | N | P50 | P95 | Cost / query | LLM calls OK | no_match rate | Step acc. (gold) |")
    w("| :--- | :--- | :-: | :-: | :-: | :-: | :-: | :-: | :-: |")
    for k, v in r["providers"].items():
        if v.get("measured"):
            w(f"| {k} | {v['model']} | {v['n']} | {v['p50_ms']} ms | {v['p95_ms']} ms | ${v['mean_cost_usd']:.6f} | "
              f"{v.get('llm_ok_pct')}% | {v['fallback_rate_pct']}% | {_f(v.get('step_accuracy'))} |")
        else:
            reason = " ".join(str(v['reason']).split())[:140]
            w(f"| {k} | - | - | - | - | - | - | - | not measured: {reason} |")
    w("")
    w("The prototype is deliberately zero-cost: every number above comes from free, local components (open models on a "
      "CPU laptop). Hosted providers are optional plug-ins in `app/llm_client.py` and were not used for the results.")
    w("")
    w("---")
    w("")
    w("## 6. Known Edge Cases & System Limitations")
    for item in r.get("limitations", []) + LIMITATIONS:
        w(f"* {item}")
    w("")
    path.write_text("\n".join(L), encoding="utf-8")


LIMITATIONS = [
    "**Synthetic data.** Catalog, SIIS articles, queries and gold samples were generated for this prototype; SIIS menu "
    "paths follow one consistent `Settings > A > B` style, which flatters the deterministic step parser and the "
    "screen-resolution numbers. Official SIIS text with free-form phrasing will need `app/steps.py` patterns extended.",
    "**Step parser coverage.** Steps are copied from source sentences (no hallucination), so an instruction phrased as "
    "a statement rather than an imperative is skipped, and very long sentences stay as one step.",
    "**Cache false hits vs recall.** Lower τ raises paraphrase hit rate but lets semantically-near different problems "
    "(e.g. 'phone slow' vs 'phone slow after update') share a plan; see the τ sweep. Negatives are tracked separately.",
    "**Multi-symptom detection** relies on conjunction splitting (rules) or the SLM's symptom list; complaints that "
    "describe two issues without a conjunction are answered with one goal.",
    "**Categories.** `manual` also covers non-physical actions that have no Settings screen (e.g. updating apps from a "
    "store), because the contract has only three categories and manual actions may not carry deeplinks.",
    "**CPU-only latency** varies with power state (battery vs mains) and thermal throttling; the environment line above "
    "records the state during this run.",
    "**validationDeeplink** is left null: the catalog provides validation keys, but the desired target value of a "
    "toggle cannot be derived safely from the SIIS text alone.",
]


if __name__ == "__main__":
    root = Path(__file__).resolve().parents[1]
    rep = json.loads((root / "bench" / "report.json").read_text(encoding="utf-8"))
    write_metrics(rep, root / (sys.argv[1] if len(sys.argv) > 1 else "metrics.md"))
