"""Synthetic user complaints, held-out paraphrases and gold sample definitions."""

# (query, domain, siis target: str | list[str] | None, register)
QUERIES = [
    # ---- Display / Navigation
    ("The mobile phone swipe navigation moves up or down instead of left or right after downloading an app", "Navigation", "siis_d01", "formal"),
    ("swipe gestures go the wrong way after installing an app", "Navigation", "siis_d01", "casual"),
    ("navigation gestures broken", "Navigation", "siis_d01", "keyword"),
    ("how do i switch from buttons to swipe gestures", "Navigation", "siis_d01", "casual"),
    ("My screen keeps flickering", "Display", "siis_d02", "casual"),
    ("display flicker at low brightness", "Display", "siis_d02", "keyword"),
    ("screen flikers randomly its so annoying", "Display", "siis_d02", "typo"),
    ("My screen is too dark even at full brightness", "Display", "siis_d03", "casual"),
    ("screen dim", "Display", "siis_d03", "keyword"),
    ("The display turns off after a few seconds", "Display", "siis_d04", "formal"),
    ("how to make the screen stay on longer", "Display", "siis_d04", "casual"),
    ("touch screen not responding to my taps", "Display", "siis_d05", "casual"),
    ("WHY WONT MY TOUCHSCREEN WORK", "Display", "siis_d05", "frustrated"),
    ("the screen looks yellow", "Display", "siis_d06", "casual"),
    ("colours look washed out on my display", "Display", "siis_d06", "formal"),
    ("always on display not showing the clock", "Display", "siis_d07", "casual"),
    ("screen wont rotate", "Display", "siis_d08", "typo"),
    ("auto rotate not working in videos", "Display", "siis_d08", "keyword"),
    ("text is too small to read", "Display", "siis_d09", "casual"),
    ("dark mode keeps turning off by itself", "Display", "siis_d10", "casual"),
    ("phone is tapping things on its own", "Display", "siis_d11", "casual"),
    ("ghost touch problem", "Display", "siis_d11", "keyword"),
    ("scrolling looks choppy not smooth", "Display", "siis_d12", "casual"),
    # ---- Battery
    ("My battery is draining really fast", "Battery", "siis_b01", "casual"),
    ("battery drain", "Battery", "siis_b01", "keyword"),
    ("battery dies in like 3 hours this is ridiculous", "Battery", "siis_b01", "frustrated"),
    ("The battery life of my device has decreased significantly", "Battery", "siis_b01", "formal"),
    ("batery drainig fast", "Battery", "siis_b01", "typo"),
    ("phone charging very slowly", "Battery", "siis_b02", "casual"),
    ("charger not charging properly", "Battery", "siis_b02", "keyword"),
    ("fast charging stopped working", "Battery", "siis_b02", "casual"),
    ("phone gets very hot while charging", "Battery", "siis_b03", "casual"),
    ("battery drops overnight while I sleep", "Battery", "siis_b04", "casual"),
    ("loses 20 percent overnight on standby", "Battery", "siis_b04", "keyword"),
    ("battery got worse after the latest update", "Battery", "siis_b05", "casual"),
    ("wireless charger not working", "Battery", "siis_b06", "keyword"),
    ("phone stops charging at 85 percent", "Battery", "siis_b07", "casual"),
    ("why wont it charge past 80%", "Battery", "siis_b07", "frustrated"),
    ("gps is killing my battery", "Battery", "siis_b08", "casual"),
    ("phone turns off at 30 percent battery", "Battery", "siis_b09", "casual"),
    ("battery percentage not showing in status bar", "Battery", "siis_b10", "casual"),
    # ---- Camera
    ("My camera photos come out blurry", "Camera", "siis_c01", "casual"),
    ("blurry pictures", "Camera", "siis_c01", "keyword"),
    ("camera cant focus properly", "Camera", "siis_c01", "typo"),
    ("Camera failed error message", "Camera", "siis_c02", "keyword"),
    ("camera app keeps crashing when I open it", "Camera", "siis_c02", "casual"),
    ("camera shows a black screen", "Camera", "siis_c03", "casual"),
    ("flash not working on camera", "Camera", "siis_c04", "keyword"),
    ("photos look low quality and grainy", "Camera", "siis_c05", "casual"),
    ("how to turn off camera shutter sound", "Camera", "siis_c06", "casual"),
    ("video recording stops by itself", "Camera", "siis_c07", "casual"),
    ("selfies are flipped mirrored", "Camera", "siis_c08", "keyword"),
    ("my videos are super shaky", "Camera", "siis_c09", "casual"),
    # ---- Performance
    ("My phone is very slow", "Performance", "siis_p01", "casual"),
    ("phone lagging", "Performance", "siis_p01", "keyword"),
    ("The device performance has degraded and applications respond slowly", "Performance", "siis_p01", "formal"),
    ("my phone got slow after the update", "Performance", "siis_p02", "casual"),
    ("laggy after software update", "Performance", "siis_p02", "keyword"),
    ("apps keep crashing", "Performance", "siis_p03", "keyword"),
    ("apps close by themselves randomly", "Performance", "siis_p03", "casual"),
    ("storage full cant install apps", "Performance", "siis_p04", "keyword"),
    ("phone keeps freezing", "Performance", "siis_p05", "casual"),
    ("phone hangs and wont respond at all", "Performance", "siis_p05", "frustrated"),
    ("apps reload every time i switch", "Performance", "siis_p06", "casual"),
    ("phone overheats when gaming", "Performance", "siis_p07", "casual"),
    ("phone restarts randomly", "Performance", "siis_p08", "casual"),
    ("keyboard is laggy when typing", "Performance", "siis_p09", "casual"),
    ("home screen lags", "Performance", "siis_p10", "keyword"),
    # ---- Connectivity / sound / notifications / software
    ("My Wi-Fi keeps dropping", "Connectivity", "siis_n01", "casual"),
    ("wifi disconnects every few minutes", "Connectivity", "siis_n01", "casual"),
    ("bluetooth wont pair with my earbuds", "Connectivity", "siis_n02", "typo"),
    ("mobile data not working", "Connectivity", "siis_n03", "keyword"),
    ("no signal on my phone", "Connectivity", "siis_n04", "casual"),
    ("hotspot not working laptop cant connect", "Connectivity", "siis_n05", "casual"),
    ("bluetooth audio keeps cutting out", "Connectivity", "siis_n06", "casual"),
    ("wifi calling not working", "Connectivity", "siis_n07", "keyword"),
    ("gps location is inaccurate", "Connectivity", "siis_n08", "casual"),
    ("cant hear anything during calls", "Sound", "siis_s01", "casual"),
    ("not getting notifications from whatsapp", "Notifications", "siis_s02", "casual"),
    ("calls are silenced", "Notifications", "siis_s03", "keyword"),
    ("phone not vibrating", "Sound", "siis_s04", "keyword"),
    ("ringtone too quiet", "Sound", "siis_s05", "keyword"),
    ("software update keeps failing", "Software", "siis_r01", "casual"),
    ("how do I factory reset my phone", "Software", "siis_r02", "casual"),
    ("time on my phone is wrong", "Software", "siis_r04", "casual"),
    ("lift to wake stopped working", "Software", "siis_r05", "casual"),
    # ---- multi-symptom
    ("my screen flickers and the battery dies fast", "Display", ["siis_d02", "siis_b01"], "casual"),
    ("phone is slow and the battery drains quickly", "Performance", ["siis_p01", "siis_b01"], "casual"),
    ("camera photos are blurry and the flash does not work", "Camera", ["siis_c01", "siis_c04"], "casual"),
    ("wifi keeps disconnecting and bluetooth wont pair", "Connectivity", ["siis_n01", "siis_n02"], "casual"),
    ("phone overheats while charging and apps keep crashing", "Battery", ["siis_b03", "siis_p03"], "casual"),
    ("screen too dim and it turns off too fast", "Display", ["siis_d03", "siis_d04"], "casual"),
    ("storage is full and the camera stops recording video", "Performance", ["siis_p04", "siis_c07"], "casual"),
    ("phone keeps freezing and the touchscreen does not respond", "Performance", ["siis_p05", "siis_d05"], "frustrated"),
    ("no notifications and the phone does not vibrate", "Notifications", ["siis_s02", "siis_s04"], "casual"),
    ("charging is slow and phone restarts randomly", "Battery", ["siis_b02", "siis_p08"], "casual"),
    # ---- no matching SIIS entry (expected no_match)
    ("My Galaxy Watch won't sync my step count with the phone", "Other", None, "casual"),
    ("how do i transfer whatsapp chats to an iphone", "Other", None, "casual"),
    ("my screen cracked after I dropped it how much is the repair", "Other", None, "casual"),
    ("cant sign in to my samsung account", "Other", None, "casual"),
    ("s pen not writing on the screen", "Other", None, "keyword"),
    ("esim activation failed", "Other", None, "keyword"),
    ("samsung dex wont connect to my monitor", "Other", None, "casual"),
    ("card declined in samsung wallet", "Other", None, "casual"),
    ("how to unlock the bootloader", "Other", None, "keyword"),
    ("phone fell in the pool and wont turn on", "Other", None, "frustrated"),
]

# Held-out paraphrases: NEVER used for pre-warming, only for cache benchmarking.
# Keyed by the exact query text above.
HELDOUT = {
    "swipe gestures go the wrong way after installing an app": [
        "since I installed a new launcher my swipe gestures are messed up",
        "gesture navigation reversed after new app",
        "swiping to go home stopped working properly after an app install",
        "nav gestures acting weird after downloading something"],
    "My screen keeps flickering": [
        "display keeps blinking on and off",
        "my phone screen flashes and flickers constantly",
        "screen flickring non stop",
        "there is a weird flicker on my display"],
    "My screen is too dark even at full brightness": [
        "display is really dim even with brightness at max",
        "cant see the screen its so dark",
        "screen brightness is too low"],
    "The display turns off after a few seconds": [
        "screen goes black too quickly",
        "my display sleeps way too fast",
        "screen timeout is too short"],
    "touch screen not responding to my taps": [
        "touchscreen is unresponsive",
        "screen doesnt register my touches",
        "tapping the display does nothing"],
    "the screen looks yellow": [
        "display has a yellowish tint",
        "why is my screen so warm and orange",
        "screen colours look off and yellow"],
    "screen wont rotate": [
        "display stuck in portrait mode",
        "screen does not turn when I rotate the phone",
        "landscape mode not working"],
    "text is too small to read": [
        "font is tiny how do I make it bigger",
        "increase text size",
        "letters on screen too small"],
    "My battery is draining really fast": [
        "battery goes down super quick",
        "my phone battery doesnt last long anymore",
        "battery runs out very fast",
        "battry dying quickly"],
    "phone charging very slowly": [
        "takes forever to charge my phone",
        "charging speed is really slow",
        "phone charges slowly with the original charger"],
    "phone gets very hot while charging": [
        "device heats up when plugged in",
        "phone is burning hot on the charger",
        "overheating during charging"],
    "battery drops overnight while I sleep": [
        "battery drains at night when not in use",
        "lost a lot of battery overnight on idle",
        "standby battery drain is bad"],
    "phone stops charging at 85 percent": [
        "battery wont go above 85",
        "charging stops before full",
        "my phone never charges to 100 percent"],
    "My camera photos come out blurry": [
        "pictures are out of focus",
        "my photos look fuzzy",
        "camera takes blurry shots",
        "pics r blurry"],
    "Camera failed error message": [
        "camera says camera failed",
        "getting a camera failed warning",
        "camera error when opening"],
    "camera shows a black screen": [
        "camera preview is black",
        "black screen when I open the camera app",
        "camera not showing anything just black"],
    "flash not working on camera": [
        "camera flash wont fire",
        "flashlight on camera doesnt turn on",
        "no flash when taking photos"],
    "how to turn off camera shutter sound": [
        "mute camera click sound",
        "disable the shutter noise",
        "camera makes a sound when I take pictures how to stop"],
    "My phone is very slow": [
        "phone is sluggish",
        "my device became really slow",
        "everything takes ages to open on my phone",
        "fone is super slow"],
    "my phone got slow after the update": [
        "phone lags since the latest software update",
        "after updating my phone became slow",
        "performance dropped after update"],
    "apps keep crashing": [
        "applications keep force closing",
        "apps crash when I open them",
        "my apps keep shutting down"],
    "phone keeps freezing": [
        "phone freezes all the time",
        "screen freezes and gets stuck",
        "device keeps hanging up"],
    "phone restarts randomly": [
        "phone reboots by itself",
        "my phone keeps restarting on its own",
        "random reboots"],
    "My Wi-Fi keeps dropping": [
        "wifi keeps disconnecting",
        "internet connection on wifi drops out",
        "wi fi connection is unstable"],
    "bluetooth wont pair with my earbuds": [
        "bluetooth pairing fails",
        "cant connect my headphones over bluetooth",
        "earbuds not pairing"],
    "mobile data not working": [
        "4g internet not working",
        "no internet on mobile data",
        "cellular data stopped working"],
    "not getting notifications from whatsapp": [
        "notifications not showing up",
        "app notifications are missing",
        "I dont receive any alerts from apps"],
    "phone not vibrating": [
        "vibration stopped working",
        "no vibration on calls",
        "phone wont vibrate"],
    "how do I factory reset my phone": [
        "reset phone to factory settings",
        "wipe my phone completely",
        "how to erase everything and reset"],
    "phone overheats when gaming": [
        "phone gets hot while playing games",
        "overheating during gaming sessions",
        "device too hot when I play pubg"],
    "keyboard is laggy when typing": [
        "typing is slow and delayed",
        "keyboard lag",
        "samsung keyboard is slow to respond"],
    "software update keeps failing": [
        "update fails to install",
        "cant update my phone software",
        "system update error"],
}

# Unseen queries with no SIIS coverage: any cache hit on these is a false hit.
HELDOUT_NEGATIVES = [
    "my galaxy buds case wont open",
    "how to change my samsung account password",
    "where is the nearest samsung store",
    "phone screen cracked need a replacement",
    "how to enable 5g carrier aggregation on my router",
    "can I use my phone underwater for photos",
    "my smartwatch strap broke",
    "how to record the screen with internal audio on a tablet",
    "tv remote app not connecting",
    "refund for a galaxy store purchase",
    "transfer photos to my laptop over usb",
    "my phone was stolen how do I track it",
]

VARIATIONS = {
    "sample_01": [
        "Ever since I installed a new app, swiping on my phone scrolls up and down instead of going left or right.",
        "Why does my phone swipe vertically when I try to swipe sideways after downloading an app?",
        "phone swipe gestures wrong direction after app install",
        "I downloaded an application yesterday and now the swipe navigation on my Galaxy moves up or down when it should go sideways.",
        "Screen navigation gestures are misbehaving after an app download; horizontal swipes register as vertical.",
        "My phone's gesture navigation got messed up by a new app and swipes go the wrong way.",
        "What should I do when swiping left or right on my phone scrolls the screen up and down instead?",
        "Swipe navigation broken after installing app.",
        "This is so annoying - I can't swipe sideways anymore since installing that app, everything just scrolls vertically.",
        "Navigation swipes on my Samsung phone respond in the wrong axis after a recent app installation.",
    ],
    "sample_02": [
        "My phone battery drains very quickly even when I barely use it.",
        "battery dying so fast",
        "battery drain fast",
        "Why does my Galaxy lose charge so quickly?",
        "The battery on my device depletes much faster than it used to.",
        "ugh my battery is dead by lunch every single day",
        "batery draning quick",
        "How can I stop my phone battery from running out so fast?",
        "Phone battery life is really short now.",
    ],
    "sample_03": [
        "My camera photos come out blurry.",
        "pictures are blurry",
        "blurry camera photos",
        "Why are all my photos out of focus?",
        "The camera on my device produces unfocused images.",
        "seriously every pic I take is blurry",
        "camra blurry pics",
        "How do I fix blurry pictures on my Galaxy camera?",
        "Photos look fuzzy and not sharp.",
    ],
    "sample_04": [
        "My phone got slow after the update.",
        "phone slow since update",
        "slow after software update",
        "Why is my Galaxy so laggy after the latest update?",
        "Device performance has degraded following the recent software update.",
        "the new update made my phone painfully slow",
        "fone slow aftr update",
        "How do I speed up my phone after updating it?",
        "Everything lags since I installed the update.",
    ],
    "sample_05": [
        "My Galaxy Watch won't sync my step count with the phone.",
        "watch not syncing steps",
        "galaxy watch step sync",
        "Why doesn't my watch send my steps to my phone?",
        "The step data from my smartwatch does not synchronise with my device.",
        "my watch refuses to sync steps its so frustrating",
        "wach not synching steps",
        "How do I get my watch steps to show on my phone?",
        "Steps from Galaxy Watch are missing on phone.",
    ],
}
