"""Synthetic Settings deeplink catalog content (written from general One UI knowledge).

Each row: (menu path, control type, cna_description, validation key or None, message override or None).
Descriptions/messages are templated from the path so the catalog reads consistently.
"""

# Screens that SIIS articles mention but are deliberately NOT in the catalog, so the
# engine has to fall back to bixby://dummy_positive (or no deeplink) for them.
INTENTIONALLY_MISSING = [
    "Settings > Display > Touch sensitivity",
    "Settings > Advanced features > Motions and gestures",
    "Settings > Accessibility > Interaction and dexterity",
]

CATALOG = [
    # --- root / connections -------------------------------------------------------------
    ("Settings", "screen", "Main settings menu listing connections, display, battery, apps and every other settings category", None, "Open the Settings app"),
    ("Settings > Connections", "screen", "Connections menu with Wi-Fi, Bluetooth, mobile networks, data usage, hotspot and airplane mode", None, None),
    ("Settings > Connections > Wi-Fi", "toggle", "Turn Wi-Fi on or off, see available networks, connect to or forget a wireless network", "wifi_enabled", "Manage Wi-Fi networks"),
    ("Settings > Connections > Wi-Fi > Advanced settings", "screen", "Advanced Wi-Fi options such as switching to mobile data, network notifications and Wi-Fi power saving", None, None),
    ("Settings > Connections > Wi-Fi > Intelligent Wi-Fi", "screen", "Intelligent Wi-Fi features that switch networks automatically and prioritise stable connections", None, None),
    ("Settings > Connections > Bluetooth", "toggle", "Turn Bluetooth on or off, pair new devices, unpair or reconnect earbuds, speakers and car kits", "bluetooth_enabled", "Manage Bluetooth devices"),
    ("Settings > Connections > Data usage", "screen", "See how much mobile and Wi-Fi data each app uses and set data warnings", None, None),
    ("Settings > Connections > Data usage > Data saver", "toggle", "Data saver stops apps from using mobile data in the background", "data_saver_enabled", None),
    ("Settings > Connections > Data usage > Mobile data", "toggle", "Mobile data switch that allows or blocks internet over the cellular network", "mobile_data_enabled", None),
    ("Settings > Connections > Mobile networks", "screen", "Mobile network options including network mode, access point names, roaming and network operators", None, None),
    ("Settings > Connections > Mobile networks > Network mode", "screen", "Choose preferred network type such as 5G, LTE, 3G or 2G auto connect", None, "Choose preferred network type"),
    ("Settings > Connections > Mobile networks > Access Point Names", "screen", "APN settings used by the carrier for mobile data and MMS; reset APN to default", None, None),
    ("Settings > Connections > Mobile networks > Data roaming", "toggle", "Allow or block mobile data while roaming on other networks abroad", "data_roaming_enabled", None),
    ("Settings > Connections > Mobile networks > Network operators", "screen", "Select the network operator automatically or manually search for carriers", None, None),
    ("Settings > Connections > Mobile Hotspot and Tethering", "screen", "Share the phone's internet through mobile hotspot, Bluetooth tethering or USB tethering", None, None),
    ("Settings > Connections > Mobile Hotspot and Tethering > Mobile Hotspot", "toggle", "Turn the mobile hotspot on or off, change hotspot name, password and band", "hotspot_enabled", None),
    ("Settings > Connections > Airplane mode", "toggle", "Airplane mode turns off calls, mobile data, Wi-Fi and Bluetooth radios", "airplane_mode_on", None),
    ("Settings > Connections > Wi-Fi Calling", "toggle", "Make and receive calls over Wi-Fi when mobile signal is weak", "wifi_calling_enabled", None),
    ("Settings > Connections > NFC and contactless payments", "toggle", "NFC for tap to pay and sharing; choose the default payment app", "nfc_enabled", None),
    ("Settings > Connections > More connection settings", "screen", "More connection options such as nearby device scanning, printing, VPN and private DNS", None, None),
    ("Settings > Connections > More connection settings > Nearby device scanning", "toggle", "Let the phone scan for nearby devices to connect to in the background", "nearby_scanning_enabled", None),
    ("Settings > Connections > More connection settings > Private DNS", "screen", "Private DNS provider settings for encrypted domain name lookups", None, None),
    ("Settings > Location", "toggle", "Location switch for GPS and location access by apps", "location_enabled", "Manage location access"),
    ("Settings > Location > Location services", "screen", "Location services such as Google location accuracy, Wi-Fi scanning and Bluetooth scanning", None, None),
    ("Settings > Location > App permissions", "screen", "Which apps can use location all the time, only while in use, or never", None, None),
    ("Settings > Connected devices", "screen", "Connected devices menu with Quick Share, Android Auto, Samsung DeX and multi control", None, None),
    ("Settings > Connected devices > Quick Share", "screen", "Quick Share lets you send files to nearby devices and choose who can share with you", None, None),
    # --- sound & notifications ----------------------------------------------------------
    ("Settings > Sounds and vibration", "screen", "Sounds and vibration menu with sound mode, ringtone, volume, vibration and sound quality", None, None),
    ("Settings > Sounds and vibration > Sound mode", "screen", "Switch between Sound, Vibrate and Mute modes for calls and notifications", None, "Choose Sound, Vibrate or Mute"),
    ("Settings > Sounds and vibration > Volume", "slider", "Volume sliders for ringtone, media, notifications and system sounds", "volume_media", None),
    ("Settings > Sounds and vibration > Ringtone", "screen", "Choose the ringtone for incoming calls", None, None),
    ("Settings > Sounds and vibration > Vibration intensity", "slider", "Vibration strength for calls, notifications and touch interactions", "vibration_intensity", None),
    ("Settings > Sounds and vibration > System sound and vibration control", "screen", "Touch sounds, keyboard sounds, dialling keypad tones and haptic feedback", None, None),
    ("Settings > Sounds and vibration > Sound quality and effects", "screen", "Sound quality options including Dolby Atmos, equaliser and UHQ upscaler", None, None),
    ("Settings > Sounds and vibration > Sound quality and effects > Dolby Atmos", "toggle", "Dolby Atmos surround sound effect for media playback", "dolby_atmos_enabled", None),
    ("Settings > Sounds and vibration > Separate app sound", "screen", "Play sound from one app on a different audio device such as a Bluetooth speaker", None, None),
    ("Settings > Notifications", "screen", "Notifications menu with app notifications, lock screen notifications, pop-up style and Do not disturb", None, None),
    ("Settings > Notifications > App notifications", "screen", "Allow or block notifications for each app individually", None, "Choose which apps can notify you"),
    ("Settings > Notifications > Lock screen notifications", "screen", "Show or hide notification content on the lock screen", None, None),
    ("Settings > Notifications > Notification pop-up style", "screen", "Choose brief or detailed pop-up notifications and edge lighting", None, None),
    ("Settings > Notifications > Do not disturb", "toggle", "Do not disturb mutes calls and alerts; set schedules and exceptions", "dnd_enabled", None),
    ("Settings > Notifications > Do not disturb > Calls and messages", "screen", "Choose which callers and messages can reach you while Do not disturb is on", None, None),
    ("Settings > Notifications > Advanced settings", "screen", "Advanced notification options such as notification history, badges and snooze", None, None),
    ("Settings > Notifications > Advanced settings > Notification history", "toggle", "Keep a history of recent and dismissed notifications", "notification_history_enabled", None),
    # --- display ------------------------------------------------------------------------
    ("Settings > Display", "screen", "Display menu with brightness, dark mode, refresh rate, screen mode, font size, screen timeout and navigation bar", None, None),
    ("Settings > Display > Dark mode", "toggle", "Dark mode applies a dark theme to reduce eye strain and save battery", "dark_mode_enabled", None),
    ("Settings > Display > Dark mode settings", "screen", "Schedule dark mode from sunset to sunrise or at a custom time", None, None),
    ("Settings > Display > Brightness", "slider", "Screen brightness level slider", "screen_brightness", None),
    ("Settings > Display > Adaptive brightness", "toggle", "Adaptive brightness changes the screen brightness automatically based on surrounding light", "adaptive_brightness_enabled", None),
    ("Settings > Display > Extra brightness", "toggle", "Extra brightness raises the maximum brightness beyond the normal limit", "extra_brightness_enabled", None),
    ("Settings > Display > Motion smoothness", "screen", "Refresh rate setting: Adaptive up to 120 Hz for smoother motion or Standard 60 Hz to save battery", None, "Choose screen refresh rate"),
    ("Settings > Display > Eye comfort shield", "toggle", "Eye comfort shield filters blue light and warms screen colours", "eye_comfort_enabled", None),
    ("Settings > Display > Screen mode", "screen", "Screen colour mode Vivid or Natural and white balance adjustment", None, "Choose Vivid or Natural colours"),
    ("Settings > Display > Font size and style", "screen", "Change font size, font style and bold text", None, None),
    ("Settings > Display > Screen zoom", "screen", "Make on-screen items such as icons and text bigger or smaller", None, None),
    ("Settings > Display > Screen resolution", "screen", "Choose HD+, FHD+ or WQHD+ screen resolution", None, None),
    ("Settings > Display > Full screen apps", "screen", "Choose which apps use the full screen aspect ratio or hide the camera cutout", None, None),
    ("Settings > Display > Screen timeout", "screen", "How long the screen stays on before it turns off automatically", None, "Choose screen timeout length"),
    ("Settings > Display > Navigation bar", "screen", "Switch between navigation buttons and swipe gestures, button order and gesture hint", None, "Choose navigation type in Display settings"),
    ("Settings > Display > Navigation bar > More options", "screen", "Swipe gesture sensitivity and gesture type options for navigation", None, None),
    ("Settings > Display > Accidental touch protection", "toggle", "Protect the screen from accidental touches in dark places such as a pocket or bag", "accidental_touch_protection", None),
    ("Settings > Display > Show charging information", "toggle", "Show battery level and estimated charging time while charging", "charging_info_enabled", None),
    ("Settings > Display > Screen saver", "screen", "Screen saver shown while the phone is charging", None, None),
    ("Settings > Display > Edge panels", "toggle", "Edge panels shortcut handle on the side of the screen", "edge_panels_enabled", None),
    ("Quick panel > Auto rotate", "toggle", "Auto rotate switch in the Quick panel that lets the screen turn between portrait and landscape", "auto_rotate_enabled", "Turn screen rotation on or off"),
    ("Quick panel > Flashlight", "toggle", "Flashlight switch in the Quick panel", "flashlight_on", None),
    ("Settings > Wallpaper and style", "screen", "Change wallpapers, colour palette and theme", None, None),
    ("Settings > Lock screen", "screen", "Lock screen menu with screen lock type, Always On Display and lock screen widgets", None, None),
    ("Settings > Lock screen > Screen lock type", "screen", "Choose swipe, pattern, PIN or password to unlock the phone", None, None),
    ("Settings > Lock screen > Always On Display", "toggle", "Always On Display shows the clock and notifications while the screen is off", "aod_enabled", None),
    ("Settings > Lock screen > Always On Display > When to show", "screen", "Choose whether Always On Display shows always, as scheduled or only after tapping the screen", None, None),
    # --- battery ------------------------------------------------------------------------
    ("Settings > Battery", "screen", "Battery menu with battery usage, power saving, background usage limits and charging settings", None, "Check battery usage by app"),
    ("Settings > Battery > Battery usage", "screen", "Battery usage graph and which apps used the most battery since the last full charge", None, None),
    ("Settings > Battery > Power saving", "toggle", "Power saving mode limits background activity, lowers brightness and speed to extend battery life", "power_saving_enabled", None),
    ("Settings > Battery > Background usage limits", "screen", "Put unused apps to sleep and manage sleeping, deep sleeping and never sleeping apps", None, None),
    ("Settings > Battery > Background usage limits > Put unused apps to sleep", "toggle", "Automatically put apps you have not used recently to sleep", "put_unused_apps_to_sleep", None),
    ("Settings > Battery > Background usage limits > Sleeping apps", "screen", "Apps that run in the background only occasionally", None, None),
    ("Settings > Battery > Background usage limits > Deep sleeping apps", "screen", "Apps that never run in the background and only work when opened", None, None),
    ("Settings > Battery > Background usage limits > Never sleeping apps", "screen", "Apps that are always allowed to run in the background", None, None),
    ("Settings > Battery > Charging settings", "screen", "Charging options such as fast charging, fast wireless charging and battery protection", None, None),
    ("Settings > Battery > Charging settings > Fast charging", "toggle", "Fast charging for wired chargers", "fast_charging_enabled", None),
    ("Settings > Battery > Charging settings > Fast wireless charging", "toggle", "Fast charging on compatible wireless chargers", "fast_wireless_charging_enabled", None),
    ("Settings > Battery > Charging settings > Protect battery", "toggle", "Protect battery stops charging at 80 or 85 percent to extend battery lifespan", "protect_battery_enabled", None),
    ("Settings > Battery > More battery settings", "screen", "More battery options including adaptive battery and battery percentage", None, None),
    ("Settings > Battery > More battery settings > Adaptive battery", "toggle", "Adaptive battery learns app usage and limits battery for apps you rarely use", "adaptive_battery_enabled", None),
    ("Settings > Battery > More battery settings > Show battery percentage", "toggle", "Show the battery percentage in the status bar", "show_battery_percent", None),
    ("Settings > Battery > Wireless power sharing", "toggle", "Wirelessly charge another device such as earbuds or a watch from the back of the phone", "wireless_powershare_enabled", None),
    # --- device care --------------------------------------------------------------------
    ("Settings > Device care", "screen", "Device care checks battery, storage, memory and device protection and offers Optimize now", None, "Optimise your phone"),
    ("Settings > Device care > Storage", "screen", "Storage usage by files, apps and system; delete unnecessary files, duplicates and large files", None, None),
    ("Settings > Device care > Memory", "screen", "RAM usage; close background apps to free up memory", None, None),
    ("Settings > Device care > Memory > RAM Plus", "screen", "RAM Plus uses storage as virtual memory; choose its size or turn it off", None, None),
    ("Settings > Device care > Performance profile", "screen", "Performance profile Standard or Light to balance speed, heat and battery", None, None),
    ("Settings > Device care > Auto optimization", "screen", "Automatically optimise the phone daily and restart when needed", None, None),
    ("Settings > Device care > Auto optimization > Restart when needed", "toggle", "Allow the phone to restart automatically at night to keep it running smoothly", "auto_restart_enabled", None),
    ("Settings > Device care > Device protection", "screen", "Scan the phone for malware and harmful apps", None, None),
    ("Settings > Device care > Diagnostics", "screen", "Run hardware tests for the screen, sensors, battery, speakers and cameras", None, None),
    ("Settings > Device care > Battery", "screen", "Device care battery overview shortcut with usage and power saving", None, None),
    # --- apps ---------------------------------------------------------------------------
    ("Settings > Apps", "screen", "List of installed apps; open app info to force stop, clear cache, change permissions or uninstall", None, None),
    ("Settings > Apps > Default apps", "screen", "Choose default apps for browser, calls, messages and Home screen launcher", None, None),
    ("Settings > Apps > Default apps > Home app", "screen", "Choose which launcher is used as the Home screen app", None, None),
    ("Settings > Apps > Camera", "screen", "App info for the Camera app: force stop, storage, permissions and notifications", None, None),
    ("Settings > Apps > Camera > Storage", "screen", "Clear cache or clear data for the Camera app", None, None),
    ("Settings > Apps > Camera > Permissions", "screen", "Camera app permissions such as microphone, location and storage", None, None),
    ("Settings > Apps > Google Play Store", "screen", "App info for Google Play Store: storage, cache and updates", None, None),
    ("Settings > Apps > Google Play services", "screen", "App info for Google Play services: storage, battery and permissions", None, None),
    ("Settings > Security and privacy", "screen", "Security and privacy menu with biometrics, permission manager, app security and updates", None, None),
    ("Settings > Security and privacy > Permission manager", "screen", "Review which apps can access camera, microphone, location, contacts and files", None, None),
    ("Settings > Security and privacy > Biometrics", "screen", "Face recognition and fingerprint unlock settings", None, None),
    ("Settings > Security and privacy > Biometrics > Fingerprints", "screen", "Register, delete or rename fingerprints used to unlock the phone", None, None),
    # --- accessibility / advanced features ----------------------------------------------
    ("Settings > Accessibility", "screen", "Accessibility menu with vision, hearing and interaction options", None, None),
    ("Settings > Accessibility > Vision enhancements", "screen", "Vision options such as high contrast fonts, colour correction and reduce animations", None, None),
    ("Settings > Accessibility > Vision enhancements > Reduce animations", "toggle", "Reduce or remove screen animations such as transitions and zoom effects", "reduce_animations_enabled", None),
    ("Settings > Accessibility > Vision enhancements > High contrast fonts", "toggle", "Outline text to make it stand out against the background", "high_contrast_fonts", None),
    ("Settings > Accessibility > Hearing enhancements", "screen", "Hearing options such as mono audio, sound balance and live caption", None, None),
    ("Settings > Accessibility > Hearing enhancements > Mono audio", "toggle", "Combine stereo channels into one so both earbuds play the same sound", "mono_audio_enabled", None),
    ("Settings > Advanced features", "screen", "Advanced features menu with side button, video brightness, labs and one-handed mode", None, None),
    ("Settings > Advanced features > Side button", "screen", "Choose what happens when you double press or press and hold the side button", None, None),
    ("Settings > Advanced features > Video brightness", "screen", "Make videos brighter and more vivid in supported apps", None, None),
    ("Settings > Advanced features > One-handed mode", "toggle", "Shrink the screen for one-handed use with a gesture or button", "one_handed_mode", None),
    ("Game Launcher > Game Booster", "screen", "Game Booster options to prioritise performance, limit alerts and control heat during games", None, "Optimise games"),
    # --- general management / updates / reset -------------------------------------------
    ("Settings > General management", "screen", "General management menu with language, keyboard, date and time and reset options", None, None),
    ("Settings > General management > Date and time", "screen", "Set date and time manually or automatically and choose time zone", None, None),
    ("Settings > General management > Date and time > Automatic date and time", "toggle", "Use the network provided date and time", "auto_time_enabled", None),
    ("Settings > General management > Language", "screen", "Add or change the phone's display language", None, None),
    ("Settings > General management > Keyboard list and default", "screen", "Choose the default keyboard and manage installed keyboards", None, None),
    ("Settings > General management > Samsung Keyboard settings", "screen", "Samsung Keyboard options such as predictive text, auto replace and keyboard layout", None, None),
    ("Settings > General management > Samsung Keyboard settings > Reset to default settings", "screen", "Reset Samsung Keyboard settings and clear personalised predictions", None, None),
    ("Settings > General management > Reset", "screen", "Reset options: reset all settings, reset network settings, reset accessibility settings and factory data reset", None, None),
    ("Settings > General management > Reset > Reset network settings", "screen", "Reset Wi-Fi, mobile data and Bluetooth settings to default; saved networks and pairings are removed", None, None),
    ("Settings > General management > Reset > Reset all settings", "screen", "Reset all settings to default except security, language and account settings; data is kept", None, None),
    ("Settings > General management > Reset > Factory data reset", "screen", "Erase all data and restore the phone to factory settings", None, None),
    ("Settings > Software update", "screen", "Check for and install One UI and Android software updates", None, "Check for software updates"),
    ("Settings > Software update > Download and install", "screen", "Download and install the latest available software update", None, None),
    ("Settings > Software update > Auto download over Wi-Fi", "toggle", "Download software updates automatically when connected to Wi-Fi", "auto_update_wifi", None),
    ("Settings > Accounts and backup", "screen", "Manage accounts and back up or restore data with Samsung Cloud or Google", None, None),
    ("Settings > Accounts and backup > Back up data", "screen", "Back up photos, contacts, messages and settings before a reset", None, None),
    ("Settings > Digital Wellbeing and parental controls", "screen", "Screen time dashboard, app timers and bedtime mode", None, None),
    ("Settings > Modes and Routines", "screen", "Modes such as sleep, driving and work, and automated routines", None, None),
    ("Settings > Developer options", "screen", "Developer options including USB debugging and animation scales", None, None),
    # --- camera (in-app settings) -------------------------------------------------------
    ("Camera > Camera settings", "screen", "Camera app settings menu with picture formats, video options, shutter sound, grid lines and reset settings", None, "Open camera settings"),
    ("Camera > Camera settings > Scene optimizer", "toggle", "Scene optimizer adjusts colour and exposure automatically for food, landscapes and night scenes", "scene_optimizer_enabled", None),
    ("Camera > Camera settings > Picture formats", "screen", "Photo formats such as high efficiency pictures, RAW copies and picture size", None, None),
    ("Camera > Camera settings > Advanced video options", "screen", "Video options such as high efficiency video, HDR10+ and zoom-in mic", None, None),
    ("Camera > Camera settings > Video stabilization", "toggle", "Video stabilization reduces shaking in videos", "video_stabilization_enabled", None),
    ("Camera > Camera settings > Tracking auto-focus", "toggle", "Keep focus on a moving subject", "tracking_af_enabled", None),
    ("Camera > Camera settings > Auto HDR", "toggle", "Capture more detail in bright and dark areas of photos", "auto_hdr_enabled", None),
    ("Camera > Camera settings > Shutter sound", "toggle", "Play a sound when taking a picture", "shutter_sound_enabled", None),
    ("Camera > Camera settings > Save selfies as previewed", "toggle", "Save selfies as they appear in the preview without flipping them", "selfie_mirror_enabled", None),
    ("Camera > Camera settings > Grid lines", "toggle", "Show grid lines in the viewfinder to help compose shots", "grid_lines_enabled", None),
    ("Camera > Camera settings > Location tags", "toggle", "Add GPS location tags to photos and videos", "location_tags_enabled", None),
    ("Camera > Camera settings > Storage location", "screen", "Save pictures and videos to internal storage or an SD card", None, None),
    ("Camera > Camera settings > Shooting methods", "screen", "Ways to take pictures such as voice commands, floating shutter button and palm gesture", None, None),
    ("Camera > Camera settings > Reset settings", "screen", "Reset all camera settings to their defaults", None, None),
]
